### ISSUE TITLE
Loss is NaN.

### ISSUE THREAD

**Issue by vgthengane** [JH-LEE-KR/l2p-pytorch#2]
Hi @Lee-JH-KR,

Thank you for realising the PyTorch version of L2P.

I am getting the following error. Do you have any suggestions for it? 

```Loss is nan, stopping training.```

I really appreciate any help you can provide.

**Comment by Lee-JH-KR** [comment]
Hi, 
thanks for your comment.

As a result of running my code again, there was no issue like `Loss is nan`.

Did you modify the code? If you, which part did you modify?
I need more informations.

If you have any additional issue, please comment it.

Best, 
Jaeho Lee.
